# Generated by Django 3.0.5 on 2020-04-07 17:32

from django.db import migrations, models
import django.db.models.deletion
import precioussecret.service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access_name', models.CharField(db_index=True, default=precioussecret.service.models.generate_access_name, max_length=255, unique=True)),
                ('access_code', models.CharField(default=precioussecret.service.models.generate_access_code, max_length=255)),
                ('number_of_accesses', models.IntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.Resource')),
            ],
        ),
    ]
